server:
  port: 8071

spring:
  application:
    name: xm-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xiasisi/config-1911.git
          search-paths: /
          username:
          password:
          skipSslValidation: true
      label: master

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
