
server:
  port: 8090

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: xm-provider
  redis:
    database: 0
    host: localhost
    port: 6379
    timeout: 6000ms
    jedis:
      pool:
        max-active: 200
        max-wait: -1ms
        max-idle: 10
        min-idle: 0
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/1911?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
  sleuth:
    sampler:
      probability: 1
    zipkin:
      base-url: http://localhost:9411
      sender:
        type: rabbit
    rabbitmq:
      host: localhost
      port: 5672
      username: guest
      password: guest
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl